import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/molecules/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={` transition-colors duration-300 `}
      >
        <div className="container mx-auto px-4 pt-2">
          <Header />
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
